### ISSUE TITLE
Compare to / learn from / take data or params from ...

### ISSUE THREAD

**Issue by microprediction** [microprediction/pandemic#5]
Various analyses out there ...

-  http://systrom.com/blog/the-numbers-behind-social-distancing/

**Comment by microprediction** [comment]
- https://www.kaggle.com/headsortails/covid19-us-county-jhu-data-demographics

**Comment by microprediction** [comment]
For example the Murray model could be used to calibrate mortality hazards. This could enter via the initial conditions and parameters, perhaps via an alternative parametrization. However it is probably best left for stage 2 when the surrogate model is created.

**Comment by finleyexp** [comment]
In the ReadMe, you mention the SETI-like community created surrogate model. Does this mean you've created a light-weight BOINC client that installs with pip on Windows? And, if so, does it have or need a GUI?

**Comment by microprediction** [comment]
I don’t have a windows machine to test pip install of the package.

A windows executable and/or GUI of some kind would make things a lot easier for people to use.

**Comment by finleyexp** [comment]
Okay. I'll try running it on my Windows machine and let you know how it tests. 


Pardon me if this seems a silly question, on swarmpresentation.com it said
>We need help running the simulations many times for many different parameters and initial conditions. 

are the parameters and conditions pre-programmed or could they be toggled manually? 

I'm working on [Zeemz: Pandemic Patch](https://github.com/pandemic-patch) as an augmented reality, blockchain game to help reduce hospital congestion. I think that we could integrate Pandemic into Zeemz to help you run the models and to provide our users with simulations based on the decisions they make in game.

**Comment by microprediction** [comment]
You can use the library to set parameters as you wish, but by default they are chosen somewhat randomly, sprayed around a somewhat sensible starting point. Over time this will be optimized.

 






 




This message, including its attachments, contains information from Intech Investment Management LLC or one of its affiliates, which may be confidential and/or privileged. If
 it has been sent to you in error, please reply to advise the sender of the error and immediately delete this message. Thank you.
l

**Comment by finleyexp** [comment]
Okay. That's most excellent. Then my team can keep it random, while we work with AskCo19 to determine what parameters should/could change when the players make in-game decisions. I'm thinking we can trigger the simulations based on player choices (ex. social distance/no distance). 

These are the results of running it on Windows with Python 2.7:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\[username]\appdata\local\temp\pip-install-qwfvrl\pandemic\setup.py", line 1, in <module>
        import pathlib
    ImportError: No module named pathlib
    ----------------------------------------


And, these are the results of running it on Win w/ Python 3.7: 

    Starting pandemic simulation
    {'geometry': {'b': 15,
              'c': 0.24372417325489804,
              'e': 0.0005,
              'h': 2.5,
              'i': 500,
              'n': 800000,
              'p': 8,
              'r': 0.005,
              's': 0.25},
     'health': {'id': 0.00035714285714285714,
            'ip': 0.025,
            'ir': 0.07107142857142858,
            'is': 0.1,
            'pd': 0.0014285714285714286,
            'pr': 0.06857142857142857,
            'sd': 0.002142857142857143,
            'sp': 0.05800148338198824,
            'sr': 0.06928571428571428,
            'vi': 1.0},
     'motion': {'k': 3.0, 't': 24, 'w': 0.021221541234836227}}

**Comment by microprediction** [comment]
Yeah only Python3 I likely to work, not 2.  Looks like you have it working with 3.7
